site_name: WSD ESP32
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: indigo

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
          paths: [".", "./lib"]

nav:
  - Home: index.md
  - API:
      - OLED: api/oled.md
      - RGB: api/rgb.md
      - WiFi: api/wifi.md

  - Examples: examples.md
